### ISSUE TITLE
FIXED No such file or directory: 'temp/lib/arm64-v8a/libgadget.so , BUT now got another ERROR

### ISSUE THREAD

**Issue by firaki12345-cmd** [Eltion/Instagram-SSL-Pinning-Bypass#80]
@Alserxxx 
@VendorAttestation
@rajatvermaiam

**MAJOR EDIT:**

**Version 360 WORKS fine, Please follow Guide from Below Link, Thanks**

**PLEASE CLICK THIS LINK:** https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/81

**Describe the bug**  

Ok so any version after 336 we get the Below error in terminal

**version 337 onwards gives the following error**

**Logs**

```
Patching for arm64-v8a
Downloading firda-gadget-16.5.7-arm64-v8a.so.xz
[==================================================]

Traceback (most recent call last):
  File "/home/firaki/Downloads/insta/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 267, in <module>
    main()
  File "/home/firaki/Downloads/insta/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 255, in main
    download_frida_gadget(arch, frida_version)
  File "/home/firaki/Downloads/insta/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 165, in download_frida_gadget
    return extract_frida_gadget(archive_path, arch)
  File "/home/firaki/Downloads/insta/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 139, in extract_frida_gadget
    with open(filepath, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/firaki/Downloads/insta/Instagram-SSL-Pinning-Bypass/temp/lib/arm64-v8a/libgadget.so'
```

**OK Below is On how to FIX the Above Error**

**1. Open the patch_apk.py file in vscode**
**2. Make the changes to the Below function, thats all**

```
def create_temp_folder():
    delete_temp_folder()
    # os.mkdir(TEMP_FOLDER)
    os.makedirs(f"{TEMP_FOLDER}/lib/arm64-v8a", exist_ok=True)
```

**Now after fixing the above, and running the script again,we get another Error** 

```
Patching for arm64-v8a
Downloading firda-gadget-16.5.9-arm64-v8a.so.xz
[==================================================]

Patching: None
Traceback (most recent call last):
  File "/home/firaki/Downloads/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 288, in <module>
    main()
  File "/home/firaki/Downloads/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 277, in main
    inject_frida_gadget(nativelib)
  File "/home/firaki/Downloads/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 22, in inject_frida_gadget
    libnative = lief.parse(libpath)
TypeError: parse(): incompatible function arguments. The following argument types are supported:
    1. parse(raw: bytes) -> Optional[lief._lief.Binary]
    2. parse(filepath: str) -> Optional[lief._lief.Binary]
    3. parse(obj: Union[io.IOBase | os.PathLike]) -> Optional[lief._lief.Binary]

Invoked with types: NoneType
```

**Now this is mainly due to the function in patch_apk.py file below (I asked CHATGPT):**

```
def extract_libs_for_apk(apk, arch):
    libs = ["libmemalign16.so","libfb.so"]
    with ZipFile(apk) as zip_file:
        namelist = zip_file.namelist()
        for lib in libs:
            libname = "lib/{0}/{1}".format(arch, lib)
            if libname in namelist:
                print("Extracting:", libname)
                return zip_file.extract(libname, TEMP_FOLDER)
```
**the libs above are not found in the instagram version after 336**

**I Unzipped the iNSTAGRAM APK and found the following in the lib folder**

```
 18290232  1980-00-00 00:00   assets/lib/libs.spo
    48915  1980-00-00 00:00   assets/lib/metadata.txt
     5120  1980-00-00 00:00   lib/arm64-v8a/libandroid_aware_dlopen.so
    10096  1980-00-00 00:00   lib/arm64-v8a/libandroidx.graphics.path.so
    88368  1980-00-00 00:00   lib/arm64-v8a/libarcore_sdk_jni.so
   324688  1980-00-00 00:00   lib/arm64-v8a/libbreakpad.so
     7552  1980-00-00 00:00   lib/arm64-v8a/libbreakpad_cpp_helper.so
   453680  1980-00-00 00:00   lib/arm64-v8a/libc++_shared.so
    18568  1980-00-00 00:00   lib/arm64-v8a/libdistract.so
   263640  1980-00-00 00:00   lib/arm64-v8a/libfbunwindstack.so
     7880  1980-00-00 00:00   lib/arm64-v8a/libforce_dlopen.so
    21432  1980-00-00 00:00   lib/arm64-v8a/liblinkerutils.so
    11744  1980-00-00 00:00   lib/arm64-v8a/libsigmux.so
   185952  1980-00-00 00:00   lib/arm64-v8a/libsuperpack-jni.so
    11408  1980-00-00 00:00   lib/arm64-v8a/libunwindstack_binary.so
      509  1980-00-00 00:00   org/assertj/core/internal/cglib/util/words.txt
```

So anyone has any expereince on how to inject the frida in the new libs ? 

thanks 

**App info**
 - Version: com.instagram.android_352.1.0.41.100-375310081_minAPI28(arm64-v8a)(360,400,420,480dpi)_apkmirror.com.apk
 - Arch: arm64-v8a

**Device info**
- Model: AC2001 (Nord_IND)
- Android Version: 10

**Comment by vxphuongictu** [comment]
Same issue, hoping someone comes up with a solution soon.

**Comment by firaki12345-cmd** [comment]
> Same issue, hoping someone comes up with a solution soon.

hi i have got the version 360 working, the guide is here

https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/81

**Comment by vxphuongictu** [comment]
> > Same issue, hoping someone comes up with a solution soon.
> 
> hi i have got the version 360 working, the guide is here
> 
> #81

I tried but it did not worked

**Comment by firaki12345-cmd** [comment]
> > > Same issue, hoping someone comes up with a solution soon.
> > 
> > hi i have got the version 360 working, the guide is here
> > 
> > #81
> 
> I tried but it did not worked

Clear the cache and data of instagram app

And is your phone rooted ? 

What is the error you get ?

**Comment by Eltion** [comment]
I've updated the patch script and the frida script, it should work now: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass
